# Generated by Django 5.2.8 on 2025-11-22 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subfolders', to='files.documentfolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pasta de Documentos',
                'verbose_name_plural': 'Pastas de Documentos',
                'ordering': ['folder_name'],
                'unique_together': {('user', 'folder_name', 'parent_folder')},
            },
        ),
        migrations.CreateModel(
            name='PDFTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('contract', 'Contrato'), ('report', 'Relatório'), ('proposal', 'Proposta')], default='proposal', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('html_content', models.TextField()),
                ('css_content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('header_image_url', models.URLField(blank=True, null=True)),
                ('footer_image_url', models.URLField(blank=True, null=True)),
                ('watermark_url', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template PDF',
                'verbose_name_plural': 'Templates PDF',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileCreated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('txt', 'Text File'), ('xlsx', 'Excel'), ('image', 'Image')], default='pdf', max_length=20)),
                ('file_size', models.BigIntegerField()),
                ('file_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_generated', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluído'), ('failed', 'Falha')], default='completed', max_length=20)),
                ('data_used', models.JSONField(blank=True, default=dict)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='files.documentfolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='files.pdftemplate')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
                'ordering': ['-created_at'],
            },
        ),
    ]
