# Generated by Django 5.2.8 on 2025-11-21 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subfolders', to='files.documentfolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pasta de Documentos',
                'verbose_name_plural': 'Pastas de Documentos',
                'ordering': ['folder_name'],
                'unique_together': {('user', 'folder_name', 'parent_folder')},
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('txt', 'Text File'), ('xlsx', 'Excel'), ('image', 'Image')], default='pdf', max_length=20)),
                ('file_size', models.BigIntegerField()),
                ('file_path', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='files.documentfolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arquivo Enviado',
                'verbose_name_plural': 'Arquivos Enviados',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('contract', 'Contrato'), ('report', 'Relatório'), ('proposal', 'Proposta')], default='proposal', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('html_content', models.TextField()),
                ('css_content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('header_image_url', models.URLField(blank=True, null=True)),
                ('footer_image_url', models.URLField(blank=True, null=True)),
                ('watermark_url', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template PDF',
                'verbose_name_plural': 'Templates PDF',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_name', models.CharField(max_length=255)),
                ('pdf_path', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluído'), ('failed', 'Falha')], default='pending', max_length=20)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('data_used', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_pdfs', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_pdfs', to='files.pdftemplate')),
            ],
            options={
                'verbose_name': 'PDF Gerado',
                'verbose_name_plural': 'PDFs Gerados',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='FileTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
                ('color_hex', models.CharField(default='#3B82F6', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_tags', to=settings.AUTH_USER_MODEL)),
                ('files', models.ManyToManyField(blank=True, related_name='tags', to='files.fileupload')),
            ],
            options={
                'verbose_name': 'Tag de Arquivo',
                'verbose_name_plural': 'Tags de Arquivos',
                'ordering': ['tag_name'],
                'unique_together': {('user', 'tag_name')},
            },
        ),
    ]
